=== sillsdev/FieldWorks/DistFiles/Language Explorer/Import/ImportFields.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<!ELEMENT AbbreviationSignatures EMPTY>
<!ATTLIST AbbreviationSignatures
	names CDATA #REQUIRED
>
<!ELEMENT Class (Field+)>
<!ATTLIST Class
	name (Entry | Etymology | Example | Function | Picture | Pronunciation | SemanticDomain | Sense | Subentry | Variant) #REQUIRED
	partOf CDATA #REQUIRED
>
<!ELEMENT Field (Help?)>
<!ATTLIST Field
	id ID #REQUIRED
	type (date | string) #REQUIRED
	property CDATA #REQUIRED
	uiname CDATA #REQUIRED
	signature CDATA #REQUIRED
	list (no | yes) #IMPLIED
	multi (no | yes) #IMPLIED
	MDF CDATA #IMPLIED
	autofield CDATA #IMPLIED
	ref CDATA #IMPLIED
	unique CDATA #IMPLIED
>
<!ELEMENT Help (Usage?, Settings?, Mapping?, Appends?, List?, Multilingual?, Examples?, RelatedFields?, Limitations?, Extras?)>
<!ELEMENT ImportFields (AbbreviationSignatures, Class+)>
<!ELEMENT Usage (#PCDATA)>
<!ELEMENT Settings (#PCDATA)>
<!ELEMENT Mapping (#PCDATA)>
<!ELEMENT Appends (#PCDATA)>
<!ELEMENT List (#PCDATA)>
<!ELEMENT Multilingual (#PCDATA)>
<!ELEMENT Example (#PCDATA)>
<!ELEMENT RelatedFields (#PCDATA)>
<!ELEMENT Limitation (#PCDATA)>
<!ELEMENT Extra (#PCDATA)>
<!ELEMENT Examples (Example+)>
<!ELEMENT Limitations (Limitation+)>
<!ELEMENT Extras (Extra+)>

=== sillsdev/FieldWorks/DistFiles/Language Explorer/Import/ImportFields.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ImportFields PUBLIC "-//XMLmind//DTD ImportFields//EN"
"ImportFields.dtd">
<!--
	Notes on the fields and attributes:
	id: used for XSLT identification (a SFM marker maps to one of these as used as the id in the map file)
	type: data type (date and string currently)
	property: rough FW property that we store the data in
	uiname: what shows up in the Import Wizard
	signature: kind of FW object that is stored in this property
	list: 'yes' if a ref to a possiblilty list
	multi: 'yes' if this field can occur 'n' times in one hierarchy
	ref: 'yes' if a combo chooser is enabled to pick from a list.
	unique: 'yes' Only allow one of the unique fields in each instance of a class
	MDF: info about possible input SFM
	autofield: can be either an entry or sense - not specified but is determined at run time
-->
<ImportFields>
  <AbbreviationSignatures names="CmPossibility CmAnthroItem PartOfSpeech CmSemanticDomain CmLocation" />

  <Class name="Entry" partOf="records">
	<Field MDF="\a" id="allo" list="no" multi="yes" property="AlternateForms"
		   signature="MultiUnicode" type="string"
		   uiname="Alternate Form (Allomorph)">
	  <Help>
		<Usage>When you have a marker that gives an allomorph for this
		entry.</Usage>

		<Settings>Set the Language Descriptor to the language of this
		field.</Settings>

		<Mapping>No</Mapping>

		<Appends>Yes, creates an allomorph for each field.</Appends>

		<List>No</List>

		<Multilingual>Yes, for alternate vernacular writing
		systems.</Multilingual>

		<Examples>
		  <Example>\a -ed</Example>

		  <Example>\a -pped</Example>

		  <Example>\a ible +/ {ible} _ (allomorph with phonological
		  environment -- see limitations)</Example>
		</Examples>

		<Limitations>
		  <Limitation>The import process currently does not handle allomorph
		  environments. It simply imports the entire field content as a single
		  allomorph. If your field contains environment information as in the
		  last example, you'll either need to remove them prior to import,
		  manually fix them inside of Flex after import, or use an advanced
		  process to manipulate the final XML file prior to
		  import.</Limitation>

		  <Limitation>Flex currently does not interpret multiple allomorphs in
		  a single SFM field. You will either need to split these into
		  individual \a fields prior to import, or clean up the problem inside
		  of Flex.</Limitation>
		</Limitations>

		<Extras>
		  <Extra>Flex uses affix marks (e.g., the hyphens in the examples) to
		  create an affix or stem allomorph and fills in the form from the
		  field contents. The Morph Type for the allomorph is also determined
		  by the affix marks. The affix marks will then be stripped from the
		  form inside of Flex.</Extra>
		</Extras>
	  </Help>
	</Field>

	<Field id="ebib" list="no" multi="yes" property="Bibliography"
		   signature="MultiString" type="string" uiname="Bibliography (Entry)">
	  <Help>
		<Usage>When you have a marker that gives bibliographical references
		for this entry.</Usage>

		<Settings>Set the Language Descriptor to the language of this
		field.</Settings>

		<Mapping>Yes</Mapping>

		<Appends>Yes, appends field contents into a single field.</Appends>

		<List>No</List>

		<Multilingual>Yes</Multilingual>

		<Examples>
		  <Example>\bb See IJAL 20:30-35 for more information.</Example>
		</Examples>
	  </Help>
	</Field>

	<Field MDF="\lc" id="cit" list="no" multi="yes" property="CitationForm"
		   signature="MultiUnicode" type="string"
		   uiname="Citation Form (Entry)">
	  <Help>
		<Usage>When you have a marker that gives the citation form for this
		entry.</Usage>

		<Settings>Set the Language Descriptor to the language of this
		field.</Settings>

		<Mapping>No</Mapping>

		<Appends>No</Appends>

		<List>No</List>

		<Multilingual>Yes, for alternate vernacular writing
		systems.</Multilingual>

		<Examples>
		  <Example>\lc gatos</Example>

		  <Example>\lc mang- (includes default prefix affix marker)</Example>
		</Examples>

		<Limitations>
		  <Limitation>This should only be the form plus valid affix markers.
		  Affix markers are defined in the Morpheme Types list in the Lists
		  area.</Limitation>

		  <Limitation>If your \lc field includes a homograph number, it should
		  either be moved to a \hm field or removed from this
		  field.</Limitation>
		</Limitations>

		<Extras>
		  <Extra>The affix marker will be removed from the citation form
		  field, but will be used to set the Morph Type for the entry. Flex
		  shows the affix markers from the Morph Type when displaying
		  headwords.</Extra>
		</Extras>
	  </Help>
	</Field>

	<Field MDF="\cf" id="cref" list="no" multi="yes"
		   property="LexicalRelation" ref="yes" signature="Unicode"
		   type="string" uiname="Cross Reference">
	  <Help>
		<Usage>When you have a marker that specifies a cross reference to some
		other entry.</Usage>

		<Settings>Set the Language Descriptor to the language of this field
		and select or type a Lexical Reference Type. (Also see Sense: Lexical
		Function and Lexeme, Function: Lexical Function, and Sense: Lexical
		Relation.)</Settings>

		<Mapping>No</Mapping>

		<Appends>Yes, each field produces a new function.</Appends>

		<List>No (except Lexical Reference Type matches a list item)</List>

		<Multilingual>No</Multilingual>

		<Examples>
		  <Example>\cf house</Example>

		  <Example>\cf bank2 1.2 (2nd subsense of first sense of bank
		  homograph 2)</Example>

		  <Example>\cf house; cottage (don't include multiple lexemes in one
		  field)</Example>
		</Examples>

		<Limitations>
		  <Limitation>The format of the lexeme must be headword2 1.1 where an
		  optional homograph number is appended to the headword and an
		  optional sense number can be included after a space. This example
		  would search for the second homograph of headword and the first
		  subsense under the first sense. Note that the headword is the
		  citation form, if it exists, otherwise the lexeme form. If a sense
		  number is not specified, and the target is a sense instead of an
		  entry, the first sense in the entry will be used.</Limitation>

		  <Limitation>The headword should be used in this field. If an entry
		  has a citation form, it will use this when searching for the
		  headword. Otherwise it will use the lexeme form.</Limitation>

		  <Limitation>If the specified entry/sense cannot be found, an error
		  message is stored in import residue listing the
		  problem.</Limitation>

		  <Limitation>Only one cross reference is allowed per field at this
		  point. If you have multiple forms separated by a separator, you
		  should break these into individual fields prior to import, or the
		  links will fail to match the desired entries.</Limitation>
		</Limitations>

		<Extras>
		  <Extra>The Lexical Reference Type combobox allows you to select an
		  existing cross reference type. If you want, you can type in a name
		  for a new lexical reference type. If a new lexical reference type is
		  created, the name and abbreviation will both be set to the field
		  contents and it will be set to a pair mapping type with one
		  name.</Extra>

		  <Extra>A link will be set between the current entry and the entry or
		  sense specified in the field. If an existing cross reference
		  collection exists to which this can be a part, they will be merged.
		  Otherwise a new cross reference collection will be created. Thus, if
		  the current entry was sedan and it has two fields, \cf car and \cf
		  auto, all three entries could be linked to each other, depending on
		  the lexical reference type.</Extra>

		  <Extra>In Flex if you set a lexical function to one sense or entry,
		  a corresponding function will automatically be inserted in the
		  target sense or entry back to this entry.</Extra>
		</Extras>
	  </Help>
	</Field>

	<Field id="creat" list="no" multi="no" property="DateCreated"
		   signature="Time" type="date" uiname="Date Created">
	  <Help>
		<Usage>When you have a marker that gives the creation date for this
		entry.</Usage>

		<Mapping>No</Mapping>

		<Appends>No</Appends>

		<List>No</List>

		<Multilingual>No</Multilingual>

		<Examples>
		  <Example>\dc 23 Feb 2006</Example>

		  <Example>\dc January 13, 1994</Example>

		  <Example>\dc 10/23/2003</Example>
		</Examples>

		<Limitations>
		  <Limitation>This field should only contain a date in a standard
		  format that can be converted to a date using your default Windows
		  locale. Any other date format will be rejected.</Limitation>
		</Limitations>
	  </Help>
	</Field>

	<Field MDF="\dt" id="mod" list="no" multi="no" property="DateModified"
		   signature="Time" type="date" uiname="Date Modified">
	  <Help>
		<Usage>When you have a marker that gives the modification date for
		this entry.</Usage>

		<Mapping>No</Mapping>

		<Appends>No</Appends>

		<List>No</List>

		<Multilingual>No</Multilingual>

		<Examples>
		  <Example>\dt 10/12/2006</Example>

		  <Example>\dt 30 Dec 1978</Example>

		  <Example>\dt March 14, 2001</Example>
		</Examples>

		<Limitations>
		  <Limitation>This field should only contain a date in a standard
		  format that can be converted to a date using your default Windows
		  locale. Any other date format will be rejected.</Limitation>
		</Limitations>
	  </Help>
	</Field>

	<Field MDF="\hm" id="hom" list="no" multi="no" property="HomographNumber"
		   signature="Integer" type="string" uiname="Homograph Number">
	  <Help>
		<Usage>When you have a marker that records a homograph number for this
		entry.</Usage>

		<Mapping>No</Mapping>

		<Appends>No</Appends>

		<List>No</List>

		<Multilingual>No</Multilingual>

		<Examples>
		  <Example>\hm 2</Example>
		</Examples>

		<Extras>
		  <Extra>Homograph numbers are maintained automatically once inside of
		  Flex. You can always use Tools...Utilities and choose the Reassign
		  Homographs method to recalculate all homographs numbers whether or
