=== sillsdev/FieldWorks/DistFiles/Language Explorer/Configuration/DictionaryConfiguration.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<xs:element name="DictionaryConfiguration">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="ConfigurationItem" type="ConfigurationItemType" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element name="SharedItems" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ConfigurationItem" type="ConfigurationItemType" maxOccurs="unbounded" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Publications" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Publication" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="HomographConfiguration" type="HomographConfigurationType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="Pictures" type="PicturesType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required"/>
		<xs:attribute type="xs:string" name="writingSystem" use="optional"/>
		<xs:attribute type="xs:integer" name="version" use="required"/>
		<xs:attribute type="xs:date" name="lastModified"/>
		<xs:attribute type="xs:boolean" name="allPublications" use="optional"/>
		<xs:attribute type="xs:boolean" name="isRootBased" use="required"/>
	</xs:complexType>
</xs:element>
<xs:complexType name="HomographConfigurationType">
	<xs:attribute type="xs:boolean" name="showHwNumInReversalCrossRef"/>
	<xs:attribute type="xs:boolean" name="showHwNumInCrossRef"/>
	<xs:attribute type="xs:boolean" name="showHwNumber"/>
	<xs:attribute type="xs:boolean" name="showSenseNumberReversal"/>
	<xs:attribute type="xs:boolean" name="showSenseNumber"/>
	<xs:attribute type="xs:boolean" name="homographNumberBefore"/>
	<xs:attribute type="xs:string" name="customHomographNumbers"/>
	<xs:attribute type="xs:string" name="homographWritingSystem"/>
</xs:complexType>
<xs:complexType name="PicturesType">
	<xs:attribute type="alignmentType" name="alignment"/>
	<xs:attribute type="xs:float" name="width"/>
</xs:complexType>
<xs:complexType name="SenseOptionsType">
	<xs:attribute type="xs:string" name="numberStyle"/>
	<xs:attribute type="xs:string" name="numberBefore"/>
	<xs:attribute type="xs:string" name="numberingStyle"/>
	<xs:attribute type="xs:string" name="parentSenseNumberingStyle"/>
	<xs:attribute type="xs:string" name="numberAfter"/>
	<xs:attribute type="xs:boolean" name="numberSingleSense"/>
	<xs:attribute type="xs:boolean" name="showSingleGramInfoFirst"/>
	<xs:attribute type="xs:boolean" name="displayEachSenseInParagraph"/>
	<xs:attribute type="xs:boolean" name="displayFirstSenseInline"/>
</xs:complexType>
<xs:complexType name="WritingSystemOptionsType">
	<xs:sequence>
		<xs:element name="Option" type="OptionListItemType" maxOccurs="unbounded" minOccurs="0"/>
	</xs:sequence>
	<xs:attribute type="writingSystemType" name="writingSystemType" use="required"/>
	<xs:attribute type="xs:boolean" name="displayWSAbreviation" use="optional"/>
</xs:complexType>
	<xs:complexType name="WritingSystemAndParaOptionsType">
	<xs:sequence>
		<xs:element name="Option" type="OptionListItemType" maxOccurs="unbounded" minOccurs="0"/>
	</xs:sequence>
	<xs:attribute type="writingSystemType" name="writingSystemType" use="required"/>
	<xs:attribute type="xs:boolean" name="displayWSAbreviation" use="optional"/>
	<xs:attribute type="xs:boolean" name="displayInParagraph" use="optional"/>
</xs:complexType>
<xs:complexType name="ConfigurationItemType">
	<xs:sequence>
		<xs:element type="WritingSystemOptionsType" name="WritingSystemOptions" minOccurs="0"/>
		<xs:element type="WritingSystemAndParaOptionsType" name="WritingSystemAndParaOptions" minOccurs="0"/>
		<xs:element name="ListTypeOptions" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Option" type="OptionListItemType" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute type="listIdType" name="list" use="optional"/>
			</xs:complexType>
		</xs:element>
		<xs:element name="ComplexFormOptions" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Option" type="OptionListItemType" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute type="listIdType" name="list" use="optional"/>
				<xs:attribute type="xs:boolean" name="displayEachComplexFormInParagraph" use="optional"/>
			</xs:complexType>
		</xs:element>
		<xs:element type="SenseOptionsType" name="SenseOptions" minOccurs="0"/>
		<xs:element name="PictureOptions" minOccurs="0">
			<xs:complexType>
				<!-- Width and height restrictions are stored in inches. -->
				<xs:attribute type="xs:float" name="minimumHeight" use="required"/>
				<xs:attribute type="xs:float" name="minimumWidth" use="required"/>
				<xs:attribute type="xs:float" name="maximumHeight" use="required"/>
				<xs:attribute type="xs:float" name="maximumWidth" use="required"/>
				<!-- Controls where the picture is placed in relation to the entry text. -->
				<xs:attribute type="alignmentType" name="pictureLocation" use="required"/>
				<!-- Controls if multiple pictures are placed above or beside each other. -->
				<xs:attribute type="xs:boolean" name="stackPictures" use="required"/>
			</xs:complexType>
		</xs:element>
		<!-- Deprecated. Kept only for migration purposes -->
		<xs:element name="ReferringSenseOptions" minOccurs="0">
			<xs:complexType>
			   <xs:sequence>
					<xs:element type="WritingSystemOptionsType" name="WritingSystemOptions"/>
					<xs:element type="SenseOptionsType" name="SenseOptions"/>
			   </xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="GroupingOptions" minOccurs="0">
			<xs:complexType>
			   <xs:simpleContent>
					<xs:extension base="xs:string">
						<xs:attribute type="xs:boolean" name="displayGroupInParagraph" use="optional"/>
					</xs:extension>
			   </xs:simpleContent>
			</xs:complexType>
		</xs:element>
		<xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="ConfigurationItem" type="ConfigurationItemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ReferenceItem">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string"/>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:sequence>
	<xs:attribute type="xs:string" name="name" use="required"/>
	<xs:attribute type="xs:string" name="nameSuffix" use="optional"/>
	<xs:attribute type="xs:boolean" name="isEnabled" use="required"/>
	<xs:attribute type="xs:boolean" name="isDuplicate" use="optional"/>
	<xs:attribute type="xs:boolean" name="isCustomField" use="optional"/>
	<xs:attribute type="xs:boolean" name="hideCustomFields" use="optional"/>
	<xs:attributeGroup ref="itemStyle"/>
	<xs:attribute type="xs:string" name="field" use="required"/>
	<xs:attribute type="xs:string" name="subField" use="optional"/>
	<xs:attribute type="xs:string" name="cssClassNameOverride" use="optional"/>
	<xs:attribute type="xs:string" name="styleType" use="optional"/>
</xs:complexType>
<xs:attributeGroup name="itemStyle">
	<xs:attribute type="xs:string" name="style" use="optional"/>
	<xs:attribute type="xs:string" name="before" use="optional"/>
	<xs:attribute type="xs:string" name="between" use="optional"/>
	<xs:attribute type="xs:string" name="after" use="optional"/>
</xs:attributeGroup>
<xs:simpleType name="writingSystemType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="vernacular"/>
		<xs:enumeration value="analysis"/>
		<xs:enumeration value="both"/>
		<xs:enumeration value="pronunciation"/>
		<xs:enumeration value="reversal"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="listIdType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="none"/>
		<xs:enumeration value="complex"/>
		<xs:enumeration value="variant"/>
		<xs:enumeration value="sense"/>
		<xs:enumeration value="entry"/>
		<xs:enumeration value="note"/>
	</xs:restriction>
</xs:simpleType>
<xs:complexType name="OptionListItemType">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute type="xs:boolean" name="isEnabled" use="required"/>
			<xs:attribute type="xs:string" name="id" use="required"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>
<xs:simpleType name="alignmentType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="right"/>
		<xs:enumeration value="left"/>
		<xs:enumeration value="center"/>
		<xs:enumeration value="above"/>
		<xs:enumeration value="below"/>
	</xs:restriction>
</xs:simpleType>
</xs:schema>

=== sillsdev/FieldWorks/DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Bartholomew.xml
<?xml version="1.0" encoding="utf-8"?>
<DictionaryConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../Configuration/DictionaryConfiguration.xsd"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 name="Hybrid (complex forms as main entries and mini subentries)"
 version="-1"
 lastModified="2014-10-08"
 allPublications="true">
  <ConfigurationItem name="Main Entry" isEnabled="true" field="LexEntry" cssClassNameOverride="entry">
  <!-- using a different CSS Class for the main HeadWord and the HeadWords for subentries, references, and (variant|complex) forms
       prevents styles for the main HeadWord from leaking onto other HeadWords -->
    <ConfigurationItem name="Headword" isEnabled="true" style="Dictionary-Headword" before="" between=" " after="  " field="MLHeadWord" cssClassNameOverride="mainheadword">
      <WritingSystemOptions writingSystemType="vernacular" displayWSAbreviation="false">
        <Option id="vernacular" isEnabled="true" />
      </WritingSystemOptions>
    </ConfigurationItem>
    <ConfigurationItem name="Lexeme Form" isEnabled="false" before="" between=" " after=" " field="LexemeFormOA" cssClassNameOverride="lexemeform">
      <WritingSystemOptions writingSystemType="vernacular" displayWSAbreviation="false">
        <Option id="vernacular" isEnabled="true" />
      </WritingSystemOptions>
    </ConfigurationItem>
    <ConfigurationItem name="Citation Form" isEnabled="false" before="" between=" " after=" " field="CitationForm">
      <WritingSystemOptions writingSystemType="vernacular" displayWSAbreviation="false">
        <Option id="all vernacular" isEnabled="true" />
      </WritingSystemOptions>
    </ConfigurationItem>
    <ConfigurationItem name="Homograph Number" style="Homograph-Number" isEnabled="false" before="" after=" " field="HomographNumber" />
    <ConfigurationItem name="Pronunciations" isEnabled="true" before="" between=", " after=" " field="PronunciationsOS" cssClassNameOverride="pronunciations">
      <ConfigurationItem name="Pronunciation" isEnabled="true" before="[" between=" " after="] " field="Form">
        <WritingSystemOptions writingSystemType="pronunciation" displayWSAbreviation="false">
          <Option id="pronunciation" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="CV Pattern" isEnabled="false" before="" after=" " field="CVPattern" />
      <ConfigurationItem name="Tone" isEnabled="false" before="" after=" " field="Tone" />
      <ConfigurationItem name="Location" isEnabled="false" style="Dictionary-Contrasting" before="" after=" " field="LocationRA" cssClassNameOverride="location">
        <ConfigurationItem name="Abbreviation" isEnabled="true" before="" between=" " after=" " field="Abbreviation">
          <WritingSystemOptions writingSystemType="both" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
        <ConfigurationItem name="Name" isEnabled="false" before="" between=" " after=" " field="Name">
          <WritingSystemOptions writingSystemType="both" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
        <ConfigurationItem name="Alias" isEnabled="true" between=" " after=" " field="Alias">
          <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
      </ConfigurationItem>
      <ConfigurationItem name="PronounciationMedia" after=" " isEnabled="false" field="MediaFilesOS">
        <ConfigurationItem name="MediaFiles" after=" " isEnabled="false" field="MediaFileRA"/>
      </ConfigurationItem>
    </ConfigurationItem>
    <ConfigurationItem name="Etymology" isEnabled="false" before="" after=" " field="EtymologyOA" cssClassNameOverride="etymology">
      <ConfigurationItem name="Etymological Form" isEnabled="true" before="" between=" " after=" " field="Form">
        <WritingSystemOptions writingSystemType="both" displayWSAbreviation="false">
          <Option id="best vernoranal" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="Gloss" isEnabled="true" before="" between=" " after=" " field="Gloss">
        <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
          <Option id="analysis" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="Comment" isEnabled="true" before="" between=" " after=" " field="Comment">
        <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
          <Option id="analysis" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="Source" isEnabled="false" before="" after=" " field="Source" />
    </ConfigurationItem>
    <ConfigurationItem name="Senses" isEnabled="true" before="" between="  " after=" " field="SensesOS" cssClassNameOverride="senses">
      <SenseOptions numberStyle="Dictionary-SenseNumber" numberBefore="" numberingStyle="%O" numberAfter=") " numberSingleSense="false" showSingleGramInfoFirst="true" displayEachSenseInParagraph="false" />
      <ConfigurationItem name="Grammatical Info." isEnabled="true" style="Dictionary-Contrasting" before="" between="" after=" " field="MorphoSyntaxAnalysisRA" cssClassNameOverride="morphosyntaxanalysis">
        <ConfigurationItem name="Category Info." isEnabled="true" style="Classified-POS" before="" between=" " after=" " field="MLPartOfSpeech">
          <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
        <ConfigurationItem name="Slots (for Infl. Affixes)" isEnabled="false" before=": " between=", " after="" field="Slots">
          <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
          <ConfigurationItem name="Slot Names" isEnabled="true" before="" between=" " after=" " field="Name">
            <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
              <Option id="analysis" isEnabled="true" />
            </WritingSystemOptions>
          </ConfigurationItem>
        </ConfigurationItem>
        <ConfigurationItem name="Inflection Class" isEnabled="false" before="" between=" " after=" " field="MLInflectionClass">
          <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
        <ConfigurationItem name="Inflection Features" isEnabled="false" before="" after=" " field="FeaturesTSS" cssClassNameOverride="inflectionfeatures" />
        <ConfigurationItem name="Exception Features" isEnabled="false" before="" after=" " field="ExceptionFeaturesTSS" cssClassNameOverride="exceptionfeatures" />
        <ConfigurationItem name="Gram Info (Name)" isEnabled="false" between=" " after=" " field="InterlinearNameTSS" cssClassNameOverride="graminfoname" />
        <ConfigurationItem name="Gram Info (Abbrev)" isEnabled="false" between=" " after=" " field="InterlinearAbbrTSS" cssClassNameOverride="graminfoabbrev" />
      </ConfigurationItem>
      <ConfigurationItem name="Sense Type" isEnabled="false" style="Dictionary-Contrasting" before="(" after=") " field="SenseTypeRA" cssClassNameOverride="sensetype">
        <ConfigurationItem name="Abbreviation" isEnabled="true" before="" between=" " after="" field="Abbreviation">
          <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
        <ConfigurationItem name="Name" isEnabled="false" before="" between=" " after="" field="Name">
          <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
            <Option id="analysis" isEnabled="true" />
          </WritingSystemOptions>
        </ConfigurationItem>
      </ConfigurationItem>
      <ConfigurationItem name="Definition (or Gloss)" isEnabled="false" before="" between=" " after=" " field="DefinitionOrGloss">
        <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
          <Option id="all analysis" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="Definition" isEnabled="true" before="" between=" " after=" " field="Definition">
        <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
          <Option id="all analysis" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="Restrictions" isEnabled="true" style="Dictionary-Contrasting" before="(" between=" " after=") " field="Restrictions">
        <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
          <Option id="all analysis" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
      <ConfigurationItem name="Scientific Name" isEnabled="true" style="Dictionary-Contrasting" before="[" after="] " field="ScientificName" />
      <ConfigurationItem name="Gloss" isEnabled="false" before="" between=" " after=" " field="Gloss">
        <WritingSystemOptions writingSystemType="analysis" displayWSAbreviation="false">
          <Option id="all analysis" isEnabled="true" />
        </WritingSystemOptions>
      </ConfigurationItem>
