=== sillsdev/FieldWorks/DistFiles/Language Explorer/Configuration/Parts/ViewsLayout.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="LayoutInventory">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="layout">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element name="sublayout">
									<xs:complexType>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="group" type="xs:string" use="optional" />
										<xs:attribute name="style" type="xs:string" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element maxOccurs="unbounded" name="part">
									<xs:complexType mixed="true">
										<xs:sequence minOccurs="0">
											<xs:element name="indent">
												<xs:complexType>
													<xs:sequence>
														<xs:element minOccurs="0" name="sublayout">
															<xs:complexType>
																<xs:attribute name="name" type="xs:string" use="required" />
																<xs:attribute name="layoutChoiceField" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" maxOccurs="unbounded" name="part">
															<xs:complexType>
																<xs:sequence minOccurs="0">
																	<xs:element name="indent">
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element name="part">
																					<xs:complexType>
																						<xs:attribute name="ref" type="xs:string" use="required" />
																						<xs:attribute name="expansion" type="xs:string" use="required" />
																					</xs:complexType>
																				</xs:element>
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
																<xs:attribute name="ref" type="xs:string" use="optional" />
																<xs:attribute name="visibility" type="xs:string" use="optional" />
																<xs:attribute name="param" type="xs:string" use="optional" />
																<xs:attribute name="label" type="xs:string" use="optional" />
																<xs:attribute name="customFields" type="xs:string" use="optional" />
																<xs:attribute name="menu" type="xs:string" use="optional" />
																<xs:attribute name="expansion" type="xs:string" use="optional" />
																<xs:attribute name="abbr" type="xs:string" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="indent" type="xs:boolean" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="ref" type="xs:string" use="optional" />
										<xs:attribute name="ws" type="xs:string" use="optional" />
										<xs:attribute name="before" type="xs:string" use="optional" />
										<xs:attribute name="after" type="xs:string" use="optional" />
										<xs:attribute name="visibility" type="xs:string" use="optional" />
										<xs:attribute name="label" type="xs:string" use="optional" />
										<xs:attribute name="sep" type="xs:string" use="optional" />
										<xs:attribute name="showLabels" type="xs:boolean" use="optional" />
										<xs:attribute name="style" type="xs:string" use="optional" />
										<xs:attribute name="flowType" type="xs:string" use="optional" />
										<xs:attribute name="param" type="xs:string" use="optional" />
										<xs:attribute name="collapsedLayout" type="xs:string" use="optional" />
										<xs:attribute name="expansion" type="xs:string" use="optional" />
										<xs:attribute name="menu" type="xs:string" use="optional" />
										<xs:attribute name="hotlinks" type="xs:string" use="optional" />
										<xs:attribute name="notifyVirtual" type="xs:string" use="optional" />
										<xs:attribute name="singlegraminfofirst" type="xs:string" use="optional" />
										<xs:attribute name="css" type="xs:string" use="optional" />
										<xs:attribute name="wsType" type="xs:string" use="optional" />
										<xs:attribute name="lexreltype" type="xs:string" use="optional" />
										<xs:attribute name="showasindentedpara" type="xs:string" use="optional" />
										<xs:attribute name="number" type="xs:string" use="optional" />
										<xs:attribute name="numstyle" type="xs:string" use="optional" />
										<xs:attribute name="numsingle" type="xs:string" use="optional" />
										<xs:attribute name="recurseConfig" type="xs:boolean" use="optional" >
											<xs:annotation>
												<xs:documentation>
													If this attribute is set to false then the configuration for this element will
													be controlled by the layout part that is referenced. The configuration dialog will
													not have any visible options at this node.
											</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="recurseConfigLabel" type="xs:string" use="optional">
											<xs:annotation>
												<xs:documentation>
													When recurseConfig is false this option will be used to provide the user information
													about where the configuration for this node is handled.
												</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="parastyle" type="xs:string" use="optional" />
										<xs:attribute name="indent" type="xs:boolean" use="optional" />
										<xs:attribute name="forceSubentryDisplay" type="xs:boolean" use="optional">
											<xs:annotation>
												<xs:documentation>
													This flag will be read during the display of a fragment to force the display of this
													node when it would otherwise be suppressed. i.e. Senses are generally not to be displayed
													if there is a sense as the parent, but when a LexEntry is marked as minor in a RootBased
													dictionary and it is a component of the sense of another entry, the senses of the minor entry
													should be displayed.
												</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="preventnullstyle" type="xs:boolean" use="optional" />
										<xs:attribute name="customFields" type="xs:string" use="optional" />
										<xs:attribute name="hideConfig" type="xs:boolean" use="optional" />
										<xs:attribute name="comment" type="xs:string" use="optional" />
										<xs:attribute name="entrytype" type="xs:string" use="optional" />
										<xs:attribute name="field" type="xs:string" use="optional" />
										<xs:attribute name="cssNumber" type="xs:string" use="optional" />
										<xs:attribute name="disallowCharStyle" type="xs:boolean" use="optional" />
										<xs:attribute name="commandVisible" type="xs:boolean" use="optional" />
										<xs:attribute name="beforeStyle" type="xs:string" use="optional" />
										<xs:attribute name="abbr" type="xs:string" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element maxOccurs="unbounded" name="generate">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="part">
												<xs:complexType>
													<xs:sequence minOccurs="0">
														<xs:element minOccurs="0" name="if">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="obj">
																		<xs:complexType>
																			<xs:attribute name="field" type="xs:string" use="required" />
																			<xs:attribute name="layout" type="xs:string" use="required" />
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
																<xs:attribute name="target" type="xs:string" use="required" />
																<xs:attribute name="is" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="ifnot">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="obj">
																		<xs:complexType>
																			<xs:attribute name="field" type="xs:string" use="required" />
																			<xs:attribute name="layout" type="xs:string" use="required" />
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
																<xs:attribute name="target" type="xs:string" use="required" />
																<xs:attribute name="is" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="gendate">
															<xs:complexType>
																<xs:attribute name="field" type="xs:string" use="required" />
																<xs:attribute name="format" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="int">
															<xs:complexType>
																<xs:attribute name="field" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="seq">
															<xs:complexType>
																<xs:attribute name="field" type="xs:string" use="required" />
																<xs:attribute name="layout" type="xs:string" use="required" />
																<xs:attribute name="inheritSeps" type="xs:boolean" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="obj">
															<xs:complexType>
																<xs:attribute name="field" type="xs:string" use="required" />
																<xs:attribute name="layout" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="string">
															<xs:complexType>
																<xs:attribute name="field" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element minOccurs="0" name="configureMlString">
															<xs:complexType>
																<xs:attribute name="field" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="ref" type="xs:string" use="required" />
													<xs:attribute name="label" type="xs:string" use="optional" />
													<xs:attribute name="before" type="xs:string" use="optional" />
													<xs:attribute name="after" type="xs:string" use="optional" />
													<xs:attribute name="visibility" type="xs:string" use="optional" />
													<xs:attribute name="ws" type="xs:string" use="optional" />
													<xs:attribute name="sep" type="xs:string" use="optional" />
													<xs:attribute name="showLabels" type="xs:boolean" use="optional" />
													<xs:attribute name="flowType" type="xs:string" use="optional" />
													<xs:attribute name="wsType" type="xs:string" use="optional" />
													<xs:attribute name="hideConfig" type="xs:boolean" use="optional" />
													<xs:attribute name="param" type="xs:string" use="optional" />
													<xs:attribute name="beforeStyle" type="xs:string" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="class" type="xs:string" use="required" />
										<xs:attribute name="fieldType" type="xs:string" use="required" />
										<xs:attribute name="restrictions" type="xs:string" use="required" />
										<xs:attribute name="destClass" type="xs:string" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element name="span">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="string">
												<xs:complexType>
													<xs:attribute name="field" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="class" type="xs:string" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="label" type="xs:string" use="optional" />
						<xs:attribute name="css" type="xs:string" use="optional" />
						<xs:attribute name="tagForWs" type="xs:boolean" use="optional" />
						<xs:attribute name="choiceGuid" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sillsdev/FieldWorks/DistFiles/Language Explorer/Configuration/Parts/LexSenseLayouts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Manually created Layouts for LexSense. -->
<LayoutInventory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation='ViewsLayout.xsd'>
  <layout class="LexSense" type="detail" name="Normal">
	<part ref="HeavySummary" param="Summary" collapsedLayout="SummaryCollapsed" expansion="expanded" menu="mnuDataTree-Sense" hotlinks="mnuDataTree-Sense-Hotlinks" notifyVirtual="LexSenseOutline">
		<indent>
			<part ref="GlossAllA"/>
			<part ref="DefinitionAllA"/>
			<part ref="MsaCombo"/>
			<part ref="ComplexFormEntries" visibility="ifdata"/>
			<part ref="VisibleComplexFormEntries" visibility="ifdata"/>
			<part ref="Subentries" visibility="ifdata"/>
			<part ref="VariantForms" visibility="ifdata"/>
			<part ref="Examples" param="Normal"/>
			<part ref="ScientificName" label="Scientific Name"   visibility="ifdata" />
			<part ref="AnthroNoteAllA" label="Anthropology Note"   visibility="ifdata" />
			<part ref="BibliographyAllA" label="Bibliography"   visibility="ifdata" />
			<part ref="DiscourseNoteAllA" label="Discourse Note"   visibility="ifdata" />
			<part ref="EncyclopedicInfoAllA" label="Encyclopedic Info"   visibility="ifdata" />
			<part ref="GeneralNoteAllA" label="General Note"   visibility="ifdata" />
			<part ref="GrammarNoteAllA" label="Grammar Note"   visibility="ifdata" />
			<part ref="PhonologyNoteAllA" label="Phonology Note"   visibility="ifdata" />
			<part ref="RestrictionsAllA"   visibility="ifdata" />
			<part ref="SemanticsNoteAllA" label="Semantics Note"   visibility="ifdata" />
			<part ref="SocioLinguisticsNoteAllA" label="Sociolinguistics Note"   visibility="ifdata" />
			<part ref="Source"   visibility="ifdata" />
			<part ref="UsageTypes"   visibility="ifdata" />
			<part ref="ReversalEntries"   visibility="ifdata" />
			<part ref="SenseType"   visibility="ifdata" />
			<part ref="DomainTypes"   visibility="ifdata" />
			<part ref="PublishIn"   visibility="ifdata" />
			<!-- part ref="ThesaurusItems" label="Thesaurus Items"/ -->

			<part ref="SemanticDomains"   visibility="always" />
			<part ref="AnthroCodes"   visibility="ifdata" />
	  <!-- part ref="Appendixes"/ -->
			<part ref="Status"   visibility="ifdata" />
			<part ref="CurrentLexReferences"/>
			<part ref="ImportResidue" label="Import Residue" visibility="ifdata"/>
			<part ref="Pictures" param="Normal"/>
	  <!-- Special part to indicate where custom fields should be inserted at.  Handled in Common.Framework.DetailControls.DataTree -->
			<part customFields="here" />
			<part ref="Senses" label="SubSenses" param="Normal" menu="mnuDataTree-Subsenses"/>
	</indent>
	</part>
  </layout>

	<layout class="LexExampleSentence" type="detail" name="Normal">
		<part ref="ExampleAllV" label="Example" expansion="expanded">
			<indent>
				<part ref="TranslationsAllA" expansion="expanded" param="TranslationAndType"/>
				<part ref="Reference"/>
				<part customFields="here" />
			</indent>
		</part>
		<part ref="PublishIn"   visibility="ifdata" />
	</layout>

	<layout class="CmPicture" type="detail" name="Normal">
		<part ref="Picture" label="Picture"/>
		<part ref="Thumbnail" label="Thumbnail" visibility="never"/>
		<part ref="CaptionA" label="Caption"/>
		<part ref="FileName" label="File"/>
	</layout>
	<layout class="CmFile" type="detail" name="Normal">
		<part ref="FileName" label="File"/>
	</layout>

	<!-- This layout is used by the Find Example Sentence dialog. -->
	<layout class="LexExampleSentence" type="jtview" name="publicationNew">
		<part ref="ExamplePub" label="Example" before="" after="" visibility="ifdata" ws="all vernacular" sep=" " showLabels="false" style="Dictionary-Vernacular"/>
		<part ref="TranslationsPub" label="Translations" before="" after="" visibility="ifdata" sep=""/>
	</layout>

	<layout class="CmTranslation" type="detail" name="TranslationAndType">
		<part ref="TranslationAllA">
			<indent>
				<part ref="Type"/>
			</indent>
		</part>
	</layout>

	<layout class="LexReference" type="detail" name="ShowSingleReference">
		<part ref="ShowSingleReference"/>
	</layout>

	 <layout class="LexSense" type="jtview" name="CrossRefPub">
		<part ref="OwnerOutlinePub" label="Referenced Sense Headword" before="" after=" " visibility="ifdata" ws="vernacular" sep=" " showLabels="false" style="Dictionary-CrossReferences"/>
		<part ref="GlossPub" label="Gloss" before="" after=" " visibility="never" ws="all analysis" sep=" " showLabels="false"/>
	 </layout>

	<layout class="LexSense" type="jtview" name="classifiedDict">
		<sublayout name="classifiedDictI1" group="para" style="Classified-Item"/>
	</layout>
	<layout class="LexSense" type="jtview" name="classifiedDictI1">
		<part ref="OwnerOutlinePub" label="Referenced Sense Headword" before="" after=" " visibility="ifdata" ws="vernacular" sep=" " showLabels="false" style="Classified-Headword"/>
		<part ref="MorphoSyntaxAnalysisPub" label="Category" before="" after=" " visibility="ifdata" style="Classified-POS"/>
		<!-- Show the definition if it exists, otherwise show the gloss. -->
		<part ref="SmartDefinitionPub" label="Definition" before="" after=" " visibility="ifdata" ws="analysis" sep=" " showLabels="false" style="Classified-Defn"/>
	</layout>

	<!-- STUFF ADDED FOR NEW CONFIGURATION WORK -->

	<layout class="LexSense" type="jtview" name="publishStem_AsPara">
		<sublayout name="publishStem"/>
	</layout>
	<layout class="LexSense" type="jtview" name="publishStem">
		<part ref="MorphoSyntaxAnalysisConfig" label="Grammatical Info." before="" after=" " sep="" visibility="ifdata" style="Dictionary-Contrasting" singlegraminfofirst="yes" param="publishStem" css="grammatical-info"/>
		<part ref="SenseTypeConfig" label="Sense Type" before="(" after=") " visibility="ifdata" style="Dictionary-Contrasting" param="publishStemSenseType" css="sense-type"/>
		<part ref="SmartDefinitionPub" label="Definition (or Gloss)" before="" after=" " visibility="ifdata" ws="analysis" wsType="analysis" sep=" " showLabels="false" css="definition"/>
		<part ref="DefinitionPub" label="Definition" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="GlossPub" label="Gloss" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="ExamplesConfig" label="Examples" before="" after=" " sep="  " visibility="ifdata" param="publishStem" css="examples"/>
		<part ref="EncyclopedicInfoPub" label="Encyclopedic Info." before="[" after="] " visibility="ifdata" ws="all analysis" wsType="analysis" sep=" " css="encyclopedic-info"/>
		<part ref="RestrictionsPub" label="Restrictions" before="Restrictions: " after="] " visibility="ifdata" ws="all analysis" wsType="analysis" sep=" " css="restrictions"/>
		<part ref="LexReferencesConfig" label="Lexical Relations" before="" after=". " sep="; " visibility="ifdata" param="publishStemSenseRef" css="relations" lexreltype="sense"/>
		<part ref="VariantFormsConfig" label="Variants of Sense" before="(" after=") " sep="; " visibility="ifdata" param="publishStemSenseVariantRef" css="sense-variantrefs"/>
		<part ref="AnthroNotePub" label="Anthropology Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="BibliographyPub" label="Bibliography" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="DiscourseNotePub" label="Discourse Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="PhonologyNotePub" label="Phonology Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="GrammarNotePub" label="Grammar Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="SemanticsNotePub" label="Semantics Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="SocioLinguisticsNotePub" label="Sociolinguistics Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="GeneralNotePub" label="General Note" before="" after=" " visibility="never" ws="all analysis" wsType="analysis" sep=" " showLabels="false"/>
		<part ref="ScientificName" label="Scientific Name" before="" after=" " visibility="ifdata" css="scientific-name"/>
		<part ref="Source" label="Source" before="" after=" " visibility="never"/>
		<part ref="SemanticDomainsConfig" label="Semantic Domains" before="(sem. domains: " after=".) " sep=", " visibility="ifdata" param="publishStemSemDom" css="semantic-domains"/>
		<part ref="AnthroCodesConfig" label="Anthropology Categories" before="anthro. codes " after=" " visibility="never" sep=", " param="publishStemAnthro"/>
		<part ref="DomainTypesConfig" label="Academic Domains" before="ac. domains: " after=" " visibility="ifdata" sep=", " param="publishStemDomainType" css="domain-types"/>
		<part ref="UsageTypesConfig" label="Usages" before="{" after="} " visibility="ifdata" sep=", " param="publishStemUsageType" css="usage-types"/>
		<part ref="StatusConfig" label="Status" before=" status " after=" " visibility="never" param="publishStemStatus" css="status"/>
		<generate class="LexSense" fieldType="mlstring" restrictions="customOnly">
			<part ref="$child" label="$label" before="" after=" " visibility="never" ws="$wsName" sep=" " showLabels="false">
				<configureMlString field="$fieldName" />
			</part>
		</generate>
		<generate class="LexSense" fieldType="simplestring" restrictions="customOnly">
			<part ref="$child" label="$label" before="" after=" " visibility="never">
				<string field="$fieldName" />
			</part>
		</generate>
		<generate class="LexSense" fieldType="refatom" restrictions="customOnly">
